### ISSUE TITLE
达梦配置文件 关于内存池总量和内存池已使用量获取失败

### ISSUE THREAD

**Issue by KnightBlood** [NoahAmethyst/sql_zh_exporter#1]
达梦版本 8.1.1.88
在表V$SYSSTAT 中不存在 ID 177和178 导致俩最后俩sql执行获取 数据异常
请问 原sql 中涉及到几个id 114 115 145 144 116 143 142 178 177 分别对应的name是什么

**Comment by NoahAmethyst** [comment]
114：表空间中的块数
115：表空间中的空闲块数
145：表空间中的字节数
144：表空间中的空闲字节数
116：数据文件中的块数
143：数据文件中的空闲块数
142：数据文件中的字节数
178：数据文件中的空闲字节数
177：数据文件中的最大块数

本回答由BingChat搜索提供：
参考链接：
https://blog.csdn.net/qq_37358909/article/details/109634343
https://eco.dameng.com/document/dm/zh-cn/faq/faq-errorcode.html
https://blog.csdn.net/qq_39631768/article/details/108516557
